[target.i686-linux-android]
linker = "D:/Apps/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android27-clang++.cmd"

[target.aarch64-linux-android]
linker = "D:/Apps/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android27-clang++.cmd"

[target.armv7-linux-androideabi]
linker = "D:/Apps/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi27-clang++.cmd"

[target.x86_64-linux-android]
linker = "D:/Apps/Android/Sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android27-clang++.cmd"
