[package]
name = "triangle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
exposed = { path = "../../exposed" }
exposed-gl = { path = "../../exposed-gl" }
gl = "0.14.0"
